# Generated by Django 4.0.4 on 2022-05-07 04:18

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=64, unique=True, verbose_name='asset_id')),
                ('asset_type', models.CharField(max_length=128, verbose_name='asset_type')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('created_at', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
            ],
        ),
    ]
