# Generated by Django 4.0.4 on 2022-05-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_data',
            name='created_at',
            field=models.IntegerField(verbose_name='created_at'),
        ),
    ]
