# Generated by Django 4.0.4 on 2022-05-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0004_alter_asset_data_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_data',
            name='description',
            field=models.CharField(max_length=256, null=True, verbose_name='description'),
        ),
    ]
